name: CommandStick
version: '${project.version}'
main: net.nutchi.commandstick.CommandStick
api-version: '1.16'
author: Nutchi
description: A stick as a shortcut for typing a command
commands:
  commandstick:
    aliases: [ cstick ]
