name: CommandStick
version: '${project.version}'
main: com.github.e2318501.commandstick.CommandStick
api-version: '1.16'
author: e2318501
description: Swing a stick to execute a Minecraft command
commands:
  commandstick:
    aliases: [ cstick ]
